title: RubyZG
description: Zagreb Ruby User Group - Connecting Ruby developers in Croatia
baseurl: ""
url: "https://rubyzg.org"

markdown: kramdown
highlighter: rouge
permalink: pretty
future: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  events:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"

exclude:
  - scripts
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
